// Generated by bitfab-plugin-lib/src/flows/commandWrappers.ts. Do not edit directly.
import { runReadReplayStatus } from "bitfab-plugin-lib"
import { platform } from "../platform.js"

runReadReplayStatus(platform).catch((err) => {
  console.error("Read replay status failed:", err.message)
  process.exit(1)
})
