// Generated by bitfab-plugin-lib/src/flows/commandWrappers.ts. Do not edit directly.
import { runSwitchOrg } from "bitfab-plugin-lib"
import { platform } from "../platform.js"

runSwitchOrg(platform).catch((err) => {
  console.error("Org switch failed:", err.message)
  process.exit(1)
})
